import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useUnlock } from '../unlock-react/useUnlock'

export default function Home() {
  const { user, authenticate, checkout, isAuthorized, loading, memberships, deauthenticate } = useUnlock({
    locks: {
      '0x18aaD00B43B513Fa097A1De473cAEFA7F1Afe694': {
        network: 5
      },
      '0x0CA4aD00051663c26e0b1B8814aF925657eE5BA2': {
        network: 5
      },
      '0x2513DDA073188540221D1d92Ff0e95fa327A3081': {
        network: 4
      }
    }
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!loading && <main className={styles.main}>
        <h1 className={styles.title}>
          👋 Welcome
        </h1>

        {!user && <p>
          <button onClick={() => authenticate()}>Authenticate!</button>
        </p>}

        {!isAuthorized && user && <>
          <p>
            Welcome {user} <button onClick={() => deauthenticate()}>x</button><br />
          </p>
          <p>
            <button onClick={() => checkout()}>Purchase a membership!</button>
          </p>
        </>}

        {isAuthorized &&

          <p className={styles.description}>
            🎉 Congrats! You have at least one valid membership!
          </p>

        }
      </main>}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
